### ISSUE TITLE
fix readme link

### ISSUE THREAD

**Issue by adammwilson** [usa-npn/rnpn-old#1]
Just explored and found the new version of rnpn - great!

FYI, the readme link points at a different repo and should probably be updated:
`devtools::install_github("usa-npn/rnpn")`
instead of
`devtools::install_github("ropensci/rnpn")`

**Comment by npnlee85** [comment]
Thanks, Adam! Glad you were able to find the new version. It's still a WIP and among our to-dos is updating the documentation, including the README file.
Thanks for you input!

**Comment by npnlee85** [comment]
Updated README to describe the different versions of the library and how to best install them, including updating the devtools link with the usa-npn repo. Also changed and getting started code to use better examples.
