### ISSUE TITLE
npn_download_status_data returns error when coords are specified

### ISSUE THREAD

**Issue by vlandau** [usa-npn/rnpn-old#5]
Hi @npnlee85, hope things are going well. This package is great!

I'm running into an error related to the `coords` argument in `npn_download_status_data` when trying to limit a data download with bounding box coordinates.

This:
```R
library(rnpn)
year_range <- 2010:2015

npn_raw <- npn_download_status_data(
  request_source = "CSP",
  years = paste(year_range),
  species_ids = 36,
  phenophase_ids = 205, 
  coords = c(32.16138, -113.7449, 38.4318, -104.318))
```
Results in this error:
```R
Error in curl::handle_setform(h, .list = query) : 
  Unsupported value type for form field 'bottom_left_x1'.
```

Is there something obvious I'm doing wrong, or could this be a bug?

Thanks,
Vincent

**Comment by npnlee85** [comment]
This looks like a bug to me! The cURL request wants to submit those params as strings (it does work if you submit them as strings), but it makes more sense for the public interface to allow/use float values, esp. since that's what the documentation specifies.

Let me see about getting this sorted.

**Comment by vlandau** [comment]
Thanks for getting back! For now, I'll submit as strings so things are working! 

Sort of related -- it looks like the docs say to enter `coords` as `c(lower_left_y, lower_left_x, upper_right_y, upper_right_x)`, 
but I see in [the code](https://github.com/usa-npn/rnpn/blob/master/R/npn_data_download.R#L926-L931) that they might be read in this order: `lower_left_x, lower_left_y, upper_right_x, upper_right_y`? Just want to double check.

Thanks again!

**Comment by vlandau** [comment]
Related to the above (strings vs. numeric), you could just put something like this:
```
if(is.numeric(coords)) {
  coords <- paste(coords)
}
```

Right after [this line](https://github.com/usa-npn/rnpn/blob/master/R/npn_data_download.R#L926).

**Comment by npnlee85** [comment]
Good suggestion! I was just making changes to explicitly cast each value to string in the same place in the code but doing a type-check and then a list operation is much more elegant!

**Comment by npnlee85** [comment]
All right, I pushed a fix for this, try reinstalling the library and see if you still have this problem.

**Comment by vlandau** [comment]
Thanks so much! Did you happen to get a chance to check out the comment above regarding the order of the `coords` elements?

**Comment by vlandau** [comment]
No errors being thrown now! But the coords argument doesn't seem to be constraining the download (i.e. it's the same whether `coords` is `NULL` or specified)

**Comment by npnlee85** [comment]
All right give it another go. There was a dumb typo in the request creation that was causing the service not to recognize one of the required fields for filtering data by bounding box.

Just FYI there's also a WKT param that you can use to specify more complex geometries by which to filter data!

Let me know if it's working better now.

**Comment by vlandau** [comment]
Worked like a charm! Thanks for jumping on this and iterating so quickly! 

And related to my comment earlier about the order, I used the order specified in the docs (y1, x1, y2, x2), and it worked perfectly.

**Comment by vlandau** [comment]
> Just FYI there's also a WKT param that you can use to specify more complex geometries by which to filter data!

That is perfect! I didn't notice that before, but that functionality will be super valuable for my workflow. Thanks for pointing that out.

**Comment by npnlee85** [comment]
Yea, no problem, glad we could get it working. I'm glad the WKT functionality will be helpful, too. Talking geographies, you can ALSO specify a list of US states instead, if that's what makes the most sense for your use case.
I'll try to be just as responsive if you run into other issues. I did not see the comment earlier about the order of the params, but I'm glad the docs were able to sort it out for you.
